const CODIGO_ADMIN_PREMIUM = "BOXADMIN2026";
function valor(id){const el=document.getElementById(id);return el?el.value:"";}
function atualizarTexto(id,texto){const el=document.getElementById(id);if(el)el.innerText=texto;}
function gerarCodigoPremium(){const p1=Math.random().toString(36).substring(2,6).toUpperCase();const p2=Math.random().toString(36).substring(2,6).toUpperCase();const p3=Math.random().toString(36).substring(2,6).toUpperCase();return `BOX-${p1}-${p2}-${p3}`;}
function calcularDataExpiracao(plano){const data=new Date();if(plano==="mensal")data.setMonth(data.getMonth()+1);else if(plano==="trimestral")data.setMonth(data.getMonth()+3);else if(plano==="anual")data.setFullYear(data.getFullYear()+1);else data.setMonth(data.getMonth()+1);return data.toISOString();}
function verificarSenhaAdmin(campoId){const senha=valor(campoId).trim();if(senha!==CODIGO_ADMIN_PREMIUM){alert("Senha administrativa incorreta.");return false;}return true;}
async function gerarChavePremiumAdmin(){if(!verificarSenhaAdmin("senhaAdmin"))return;const nome=valor("novoPremiumNome").trim();const email=valor("novoPremiumEmail").toLowerCase().trim();const plano=valor("novoPremiumPlano")||"mensal";if(!nome||!email){alert("Preencha nome e e-mail do assinante.");return;}if(typeof db==="undefined"||!db.collection){alert("Firebase não conectado.");return;}const codigo=gerarCodigoPremium();const dataCriacao=new Date().toISOString();const dataExpiracao=calcularDataExpiracao(plano);const chavePremium={codigo,nome,email,plano,ativo:true,usado:false,status:"novo",dataCriacao,dataExpiracao,activationDeviceId:""};try{await db.collection("premiumKeys").doc(codigo).set(chavePremium);await db.collection("assinantes").doc(codigo).set({codigo,nome,email,plano,ativo:true,status:"novo",dataCriacao,dataExpiracao,ultimoUso:""});const area=document.getElementById("codigoPremiumGerado");area.innerHTML=`<div class="perfil-box"><h3>✅ Código Premium Gerado</h3><p><strong>Nome:</strong> ${nome}</p><p><strong>E-mail:</strong> ${email}</p><p><strong>Plano:</strong> ${plano}</p><p><strong>Código:</strong></p><input value="${codigo}" readonly><p><strong>Expira em:</strong> ${new Date(dataExpiracao).toLocaleDateString("pt-BR")}</p></div>`;alert("Código Premium gerado com sucesso!");carregarAssinantesPremium(true);}catch(erro){console.error("Erro ao gerar chave Premium:",erro);alert("Erro ao gerar chave Premium.");}}
function statusAssinatura(chave){if(!chave.ativo)return"inativo";if(chave.dataExpiracao&&new Date()>new Date(chave.dataExpiracao))return"vencido";return chave.status||"ativo";}
async function carregarAssinantesPremium(ignorarSenha=false){if(!ignorarSenha&&!verificarSenhaAdmin("senhaPainelAdmin"))return;const area=document.getElementById("listaAssinantesPremium");if(!area)return;if(typeof db==="undefined"||!db.collection){area.innerHTML="<p>Firebase não conectado.</p>";return;}area.innerHTML="<p>Carregando assinantes...</p>";try{const snapshot=await db.collection("premiumKeys").get();const assinantes=[];snapshot.forEach(doc=>assinantes.push({id:doc.id,...doc.data()}));assinantes.sort((a,b)=>String(b.dataCriacao||"").localeCompare(String(a.dataCriacao||"")));const total=assinantes.length;const ativos=assinantes.filter(a=>statusAssinatura(a)==="ativo"||statusAssinatura(a)==="novo").length;const vencidos=assinantes.filter(a=>statusAssinatura(a)==="vencido").length;const inativos=assinantes.filter(a=>statusAssinatura(a)==="inativo").length;atualizarTexto("assinantesTotal",total);atualizarTexto("assinantesAtivos",ativos);atualizarTexto("assinantesVencidos",vencidos);atualizarTexto("assinantesInativos",inativos);if(assinantes.length===0){area.innerHTML="<p>Nenhum assinante encontrado.</p>";return;}area.innerHTML=assinantes.map(a=>{const status=statusAssinatura(a);const validade=a.dataExpiracao?new Date(a.dataExpiracao).toLocaleDateString("pt-BR"):"Sem validade";const criado=a.dataCriacao?new Date(a.dataCriacao).toLocaleDateString("pt-BR"):"Sem data";const ultimoUso=a.ultimoUso?new Date(a.ultimoUso).toLocaleDateString("pt-BR"):"Nunca usado";return `<div class="post"><h3>👤 ${a.nome||"Sem nome"}</h3><p><strong>E-mail:</strong> ${a.email||"Sem e-mail"}</p><p><strong>Plano:</strong> ${a.plano||"mensal"}</p><p><strong>Status:</strong> ${status}</p><p><strong>Código:</strong> ${a.codigo||a.id}</p><p><strong>Criado em:</strong> ${criado}</p><p><strong>Expira em:</strong> ${validade}</p><p><strong>Último uso:</strong> ${ultimoUso}</p><button onclick="renovarAssinante('${a.id}','${a.plano||"mensal"}')">🔄 Renovar</button><button onclick="reativarAssinante('${a.id}')">✅ Reativar</button><button class="btn-excluir" onclick="desativarAssinante('${a.id}')">🚫 Desativar</button><button onclick="liberarDispositivo('${a.id}')">📱 Liberar dispositivo</button></div>`;}).join("");}catch(erro){console.error("Erro ao carregar assinantes:",erro);area.innerHTML="<p>Erro ao carregar assinantes.</p>";}}
async function renovarAssinante(codigo,planoAtual){if(!verificarSenhaAdmin("senhaPainelAdmin"))return;const plano=prompt("Plano para renovar: mensal, trimestral ou anual",planoAtual||"mensal");if(!plano)return;const dataExpiracao=calcularDataExpiracao(plano);try{await db.collection("premiumKeys").doc(codigo).update({ativo:true,status:"ativo",plano,dataExpiracao});await db.collection("assinantes").doc(codigo).set({ativo:true,status:"ativo",plano,dataExpiracao},{merge:true});alert("Assinatura renovada.");carregarAssinantesPremium(true);}catch(erro){console.error("Erro ao renovar:",erro);alert("Erro ao renovar assinatura.");}}
async function reativarAssinante(codigo){if(!verificarSenhaAdmin("senhaPainelAdmin"))return;try{await db.collection("premiumKeys").doc(codigo).update({ativo:true,status:"ativo"});await db.collection("assinantes").doc(codigo).set({ativo:true,status:"ativo"},{merge:true});alert("Assinante reativado.");carregarAssinantesPremium(true);}catch(erro){console.error("Erro ao reativar:",erro);alert("Erro ao reativar assinante.");}}
async function desativarAssinante(codigo){if(!verificarSenhaAdmin("senhaPainelAdmin"))return;if(!confirm("Deseja desativar este assinante?"))return;try{await db.collection("premiumKeys").doc(codigo).update({ativo:false,status:"inativo"});await db.collection("assinantes").doc(codigo).set({ativo:false,status:"inativo"},{merge:true});alert("Assinante desativado.");carregarAssinantesPremium(true);}catch(erro){console.error("Erro ao desativar:",erro);alert("Erro ao desativar assinante.");}}
async function liberarDispositivo(codigo){if(!verificarSenhaAdmin("senhaPainelAdmin"))return;if(!confirm("Deseja liberar este código para ativar em outro dispositivo?"))return;try{await db.collection("premiumKeys").doc(codigo).update({activationDeviceId:"",usado:false});alert("Dispositivo liberado. O assinante poderá ativar novamente.");carregarAssinantesPremium(true);}catch(erro){console.error("Erro ao liberar dispositivo:",erro);alert("Erro ao liberar dispositivo.");}}
window.gerarChavePremiumAdmin=gerarChavePremiumAdmin;window.carregarAssinantesPremium=carregarAssinantesPremium;window.renovarAssinante=renovarAssinante;window.reativarAssinante=reativarAssinante;window.desativarAssinante=desativarAssinante;window.liberarDispositivo=liberarDispositivo;console.log("✅ Admin Premium v1.1 carregado.");
